Traceback (most recent call last):
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/wimdavies/Projects/vanda-docs/etc-docs/api-book/.venv/lib/python3.10/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
sys.path.append("/srv/explore-the-collections/code/ivpy/src/")
from ivpy import attach,show,compose,montage,histogram,scatter
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-0ff62b7c410c>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0msys[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0msys[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0;34m"/srv/explore-the-collections/code/ivpy/src/"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0mivpy[0m [0;32mimport[0m [0mattach[0m[0;34m,[0m[0mshow[0m[0;34m,[0m[0mcompose[0m[0;34m,[0m[0mmontage[0m[0;34m,[0m[0mhistogram[0m[0;34m,[0m[0mscatter[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mModuleNotFoundError[0m: No module named 'ivpy'
ModuleNotFoundError: No module named 'ivpy'

